global:
  arguments: 
    aws_default_region: us-east-2
  metadata:   
    labels:
       default: 
         environment: demo
         purpose: test
         cloud: aws
    matchSelectors:
       server_info:
         match_labels:
           environment: demo
           purpose: test
           cloud: aws
         resource_type: server
infrastructure:
   jenkins_server:
       stack_name: williaumwu:::jenkins_on_ec2
       arguments:
          hostname: config0-demo-jenkins
          ssh_key_name: config0-demo
          public_ip: selector:::server_info::public_ip
       metadata:
          labels:
            - default
          matchSelectors:
            - server_info
